import React, { useState } from 'react';

<div className="bg-[#EF4444]/10 border-b border-[#EF4444]/20 py-2 text-center">
    <p className="text-[10px] uppercase tracking-widest text-[#EF4444] font-bold">PUBLIC SIMULATION MODE // ENTERPRISE DATA AUDIT REQUIRED</p>
</div>
export default function PurificationMatrix() {
  const [dividendIncome, setDividendIncome] = useState<number>(15000);
  const [nonCompliantRatio, setNonCompliantRatio] = useState<number>(4.5); // Standard average % for mixed-source

  const calculatePurification = () => {
    // The amount that must be stripped and donated
    const purificationLiability = dividendIncome * (nonCompliantRatio / 100);
    // The fully cleansed, retained liquidity
    const cleansedYield = dividendIncome - purificationLiability;

    return { purificationLiability, cleansedYield };
  };

  const results = calculatePurification();

  return (
    <div className="min-h-screen bg-[#0A1128] text-[#E2E8F0] font-sans selection:bg-[#1C2541] flex flex-col">
      
      {/* Navigation & Status Header */}
      <header className="max-w-4xl mx-auto w-full px-6 pt-12 pb-8 border-b border-[#94A3B8]/20">
        <div className="flex justify-between items-center mb-12">
          <a href="/digital/calculator" className="text-xs font-bold tracking-[0.2em] text-[#94A3B8] hover:text-[#FFFFFF] transition font-mono uppercase">
            ← Return to Public Utilities
          </a>
          <div className="text-xs tracking-widest font-mono flex items-center gap-2 bg-[#1C2541]/50 px-3 py-1.5 rounded border border-[#94A3B8]/20">
            <span className="w-2 h-2 rounded-full bg-[#E2E8F0] animate-pulse shadow-[0_0_8px_#E2E8F0]"></span>
            <span className="text-[#E2E8F0] font-bold">COMPLIANCE_NODE</span>
          </div>
        </div>

        <div>
          <h1 className="text-3xl font-serif text-[#FFFFFF] uppercase tracking-[0.1em]">Purification Matrix</h1>
          <p className="text-[#94A3B8] font-mono text-xs mt-3 tracking-widest uppercase">
            DIVIDEND COMPLIANCE & CAPITAL CLEANSING
          </p>
        </div>
      </header>

      <main className="max-w-4xl mx-auto w-full px-6 py-12 flex-1">
        
        {/* Operational Mandate */}
        <section className="bg-[#111C3A] p-6 border border-[#E2E8F0]/10 rounded-xl mb-12">
          <p className="text-sm font-light text-[#94A3B8] leading-relaxed">
            This utility isolates the non-compliant fractional revenue generated by mixed-source equities (e.g., fractional interest or impermissible operations). By mathematically separating this liability, you ensure your retained liquidity remains pure and structurally sound for reinvestment.
          </p>
        </section>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          
          {/* Inputs */}
          <section className="bg-[#111C3A] p-8 rounded border border-[#94A3B8]/20 shadow-xl">
            <h3 className="text-xs font-mono mb-6 text-[#FFFFFF] tracking-widest uppercase border-b border-[#94A3B8]/20 pb-4">Extraction Parameters</h3>
            
            <div className="mb-6">
              <label className="block text-[9px] uppercase tracking-widest mb-2 text-[#94A3B8]">Gross Dividend Yield Received</label>
              <input 
                type="number" 
                value={dividendIncome} 
                onChange={(e) => setDividendIncome(Number(e.target.value))} 
                className="w-full p-3 bg-[#0A1128] border border-[#94A3B8]/30 text-[#FFFFFF] font-serif focus:border-[#E2E8F0] outline-none transition" 
              />
            </div>

            <div className="mb-2">
              <label className="flex justify-between text-[9px] uppercase tracking-widest mb-2 text-[#94A3B8]">
                <span>Non-Compliant Revenue Ratio</span>
                <span className="text-[#FFFFFF] font-bold">{nonCompliantRatio.toFixed(2)}%</span>
              </label>
              <input 
                type="range" 
                min="0.1" 
                max="15" 
                step="0.1"
                value={nonCompliantRatio} 
                onChange={(e) => setNonCompliantRatio(Number(e.target.value))} 
                className="w-full h-1 bg-[#0A1128] rounded-lg appearance-none cursor-pointer accent-[#E2E8F0]" 
              />
              <p className="text-[9px] font-mono text-[#94A3B8]/60 mt-3 text-right">Standard screener average: 3% - 5%</p>
            </div>
          </section>

          {/* Telemetry Dashboard */}
          <section className="space-y-6">
            
            <div className="bg-[#1C2541] border border-[#94A3B8]/20 rounded p-6">
              <h4 className="text-sm font-serif text-[#E2E8F0] mb-1">Purification Liability</h4>
              <p className="text-[10px] font-mono text-[#94A3B8] uppercase mb-4">Capital to be Extracted & Donated</p>
              <p className="text-3xl font-bold text-[#E2E8F0]">- {results.purificationLiability.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
            </div>

            <div className="bg-[#111C3A] border border-[#94A3B8]/20 rounded p-6">
              <h4 className="text-sm font-serif text-[#E2E8F0] mb-1">Cleansed Retained Yield</h4>
              <p className="text-[10px] font-mono text-[#94A3B8] uppercase mb-4">100% Compliant Reinvestment Capital</p>
              <p className="text-3xl font-bold text-[#FFFFFF]">+ {results.cleansedYield.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
            </div>

          </section>
        </div>

        {/* Technical Protocol */}
        <section className="mt-12 bg-[#111C3A] p-8 border border-[#94A3B8]/20 rounded-xl">
            <h2 className="text-xs font-mono font-bold tracking-widest uppercase text-[#E2E8F0] mb-6 border-b border-[#94A3B8]/20 pb-6">Technical Protocol: Ledger Reconciliation</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-sm font-light text-[#94A3B8] leading-relaxed">
                <div>
                    <span className="block text-[#FFFFFF] font-bold mb-2">1. Ratio Identification</span>
                    Identify the exact non-compliant revenue percentage of the specific asset via your equity screener before applying the matrix to your gross dividend yield.
                </div>
                <div>
                    <span className="block text-[#FFFFFF] font-bold mb-2">2. Philanthropic Transfer</span>
                    Immediately extract the defined "Purification Liability" from your trading ledger and transfer it directly to your Pure Legacy Foundation or equivalent charity division to complete the compliance cycle.
                </div>
            </div>
        </section>

      </main>

      {/* Footer */}
      <footer className="max-w-4xl mx-auto w-full px-6 py-8 border-t border-[#94A3B8]/10 text-[9px] font-mono text-[#94A3B8]/40 text-center uppercase tracking-widest">
        PUBLIC UTILITY // © 2026 PURE APPROACH INVESTMENTS (PTY) LTD.
      </footer>
    </div>
  );
}
